version: '3.7'

x-common-minion: &common-minion
    build:
      context: .
      dockerfile: Dockerfile.minion
    depends_on:
      - salt-master

services: 
  salt-master:
    build:
      context: .
      dockerfile: Dockerfile.master
  db-01:
    hostname: db-01
    <<: *common-minion
  db-02:
    hostname: db-02
    <<: *common-minion
  dns-01:
    hostname: dns-01
    <<: *common-minion
  dns-02:
    hostname: dns-02
    <<: *common-minion
  web-01:
    hostname: web-01
    <<: *common-minion
  web-02:
    hostname: web-02
    <<: *common-minion
